"""Database creation

Revision ID: 1aea4ca4b70e
Revises: af4b6b8caac9
Create Date: 2023-07-12 00:27:16.422965

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1aea4ca4b70e'
down_revision = 'af4b6b8caac9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        INSERT INTO flashlights (id, status, color) 
        VALUES 
          (1, 'Включен', 'Белый'),
          (2, 'Включен', 'Черный')
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
